### ISSUE TITLE
Clang cross toolchain

### ISSUE THREAD

**Issue by xsacha** [ruslo/polly#106]
Since you can cross compile just about anything with a host clang, why not add a toolchain for this?

**Comment by ruslo** [comment]
Not sure I understand the question. There are already `libcxx` and `clang-libstdcxx` toolchains.

**Comment by xsacha** [comment]
I would like something similar to compiler/gcc-cross-compiler.cmake but for clang. Just setting a variable for sysroot, etc. It just seems strange there's no toolchain for clang cross compiling.

**Comment by ruslo** [comment]
> It just seems strange there's no toolchain for clang cross compiling

Looks like nobody using/need it, see nothing strange about it :)

> I would like something similar to compiler/gcc-cross-compiler.cmake but for clang. Just setting a variable for sysroot, etc.

Feel free to add one.

**Comment by headupinclouds** [comment]
I was previously interested in building shared libraries for Linux distributions from an OS X host (Apple HW being required for iOS).  I'm not sure if that is possible.  @xsacha Do you have any thoughts?  Here are some high level cross compilation pages I found for reference:

http://clang.llvm.org/docs/CrossCompilation.html
http://llvm.org/docs/HowToCrossCompileLLVM.html

**Comment by ruslo** [comment]
>  I'm not sure if that is possible

I think I post the question on stackoverflow but looks like I delete it because of no response and no interest in further investigation.

**Comment by headupinclouds** [comment]
Related: https://github.com/ruslo/polly/issues/27

**Comment by magick777** [comment]
@xsacha I'm thinking aloud here, not done it yet, but [libfloor](https://github.com/a2flo/floor) has a good assortment of clang-based cross compilers (pitched mostly at GPGPU computing, but it should be possible to add other targets).

New to polly so not sure yet how much work it will (or won't) be to use polly to manage a load of third-party toolchains, it's more musing aloud than clear suggestion at this time, but on the face of it, sounds like what you want could leverage existing work rather than configure it all from scratch.

**Comment by headupinclouds** [comment]
@magick777 :  👍 Thanks for the libfloor reference.  (I suppose this is slightly off topic for the original post, but I have been looking for something exactly like this.)

**Comment by ruslo** [comment]
Closing inactive discussion.
