### ISSUE TITLE
XCTest support for iOS

### ISSUE THREAD

**Issue by ikliashchou** [ruslo/polly#149]
The issue with XCTest, iOS support and polly toolchain is the CMAKE_OSX_SYSROOT value.

It is set to "iphoneos", while XCTest unit testing of frameworks is allowed only for simulator. This is why XCTest symbols are not found for x86_64 architecture when trying to run the test, as all the paths are calculated from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/....

If you change CMAKE_OSX_SYSROOT to "iphonesimulator" in polly iOS toolchain, XCTest will work.

Checked on the [project](https://github.com/Kitware/CMake/tree/master/Tests/XCTest) with changed polly/iOS-10-3.cmake toolchain and it works (you have to remove from # Static lib and below from CMakeLists.txt there to make it work).

Is there a way to make XCTest work with iOS & polly toolchain without patching? It seems that changing the variable to "iphonesimulator" raises issues with building boost libraries, that is a stopper for this approach.

Thanks

**Comment by ruslo** [comment]
> It is set to "iphoneos", while XCTest unit testing of frameworks is allowed only for simulator

I can run executables from generated Xcode project on simulator even if CMAKE_OSX_SYSROOT set to `iphoneos`.

> This is why XCTest symbols are not found for x86_64 architecture when trying to run the test

May be it means the problem is in [FindXCTest](https://cmake.org/cmake/help/latest/module/FindXCTest.html) module? It should find another libraries/there should be an option to find iPhoneSimulator root?

> If you change CMAKE_OSX_SYSROOT to "iphonesimulator" in polly iOS toolchain, XCTest will work

We can use it as a workaround for iOS+simulator only toolchains. However I don't see any simulator-only toolchains, probably it's not possible to have them on practice.

> It seems that changing the variable to "iphonesimulator" raises issues with building boost libraries, that is a stopper for this approach

That is strange, what kind of issue? Do you mean building Boost with Hunter?

**Comment by ikliashchou** [comment]
> May be it means the problem is in FindXCTest module? It should find another libraries/there should be an option to find iPhoneSimulator root?
Seems to be true. If the test target is added manually from XCode then tests work correctly.

So at the moment I abandoned this approach in favor of manually generated test project and stayed with original polly toolchain.
